title: Robert L. Grossman 
author:
  name: Robert L. Grossman
  email: robert dot grossman grossman@uchicago.edu
description: > # this means to ignore newlines until "show_excerpts:"
  I am a data scientist who has been working with predictive analytics, AI
  and big data for over 20 years.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/robertgrossman/" }
    - { platform: twitter,        user_url: "https://twitter.com/BobGrossman" }


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
